version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: medicants
      POSTGRES_PASSWORD: medicants_pass
      POSTGRES_DB: medicants
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medicants"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend-medicants
    environment:
      PORT: 3000
      ADMIN_TOKEN: medicants-dashboard-2025
      DATABASE_URL: postgres://medicants:medicants_pass@db:5432/medicants
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    # IMPORTANTE: quitar "8080:80" y dejar solo expose
    expose:
      - "80"
    depends_on:
      - api

  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - web

volumes:
  pgdata:
  npm_data:
  npm_letsencrypt:
